name: stripe_platform_interface
description: Platform interface for stripe sdk
version: 11.5.1
repository: https://github.com/flutter-stripe/flutter_stripe
homepage: https://pub.dev/packages/flutter_stripe

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  meta: ^1.10.0
  plugin_platform_interface:
    git:
      url: https://github.com/akddah/flutter_stripe.git
      path: packages/stripe_platform_interface

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_lints: ^4.0.0
